<?php

namespace App\Services;

class AzurePostService extends PostService
{
    /**
     * @param int $id
     * @param string $default
     * @return string
     */
    public function showTitle(int $id, string $default) : string
    {
        return parent::showTitle($id, $default); // TODO: Change the autogenerated stub
    }
}